export const APP_VERSION = {
  APPLE_LOGIN: {
    IOS_VERSION: 13,
    APP_SERVER_VERSION: 101
  },
  BIO_LOGIN_VERSION: 102,
  AUTO_PLAY_VERSION: 103,
  IN_APP_UPDATE_VERSION: 104,
  APP_INTRODUCTION_VERSION: 106,
  APP_AUTO_LOGIN_VERSION: 107
}
